version: "3"
services:
  twiter-node-backend:
    build: . 
    ports:
      - "3000:3000"
    links:
      - "postgres:postgres"
    depends_on:
      - "postgres"
    environment:
      WAIT_HOSTS: postgres:5432
      NODE_ENV: production
  postgres:
    image: "postgres:13-alpine"
    volumes:
      - "/var/pg-data1:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
