version: "3.9"
services:
  twiter-node-backend:
    build: . 
    ports:
      - "3000:3000"
    links:
      - "postgres:postgres"
    depends_on:
      - "postgres"
  postgres:
    image: "postgres:9.6"
     
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
